name: mips-cross

on:
  push:
    branches: [ master ]
    paths: [ "flake.nix", "flake.lock" ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      #     - name: Setup Cachix
      #       uses: cachix/cachix-action@v12
      #       with:
      #         name: sandkasten
      #         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: nix build
        run: |
          set -ex
          nix build
          image=$(docker load -qi result | cut -d' ' -f3)
          docker tag "$image" base
          docker rmi "$image"
          mkdir .docker_build
          echo "FROM base" > .docker_build/Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .docker_build
          platforms: linux/amd64
          push: true
          tags: ghcr.io/thecataliastnt2k/mips-cross-builder:latest
