name: nix

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      #     - name: Setup Cachix
      #       uses: cachix/cachix-action@v12
      #       with:
      #         name: sandkasten
      #         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: custom_ip6_ras
          path: result/bin/custom_ip6_ras
